version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily", time: "04:00" }
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    labels: ["dependencies","github-actions"]
    groups:
      all:
        patterns: ["*"]