name: Cleanup Failed Workflows

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete Failed and Cancelled Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: 'all'
          delete_run_by_conclusion_pattern: 'failure,cancelled'
